Dashboard-design Done
Kleo-Network/kleo-connect pull request #54
Opened 2024-09-09 22:32 UTC by devowl03

2024-09-11 22:43 UTC, devowl03 commented
![kleo 3](https://github.com/user-attachments/assets/a03444d3-6710-43cd-8213-b0818db48e1e)
![kleo 2](https://github.com/user-attachments/assets/cdfc227d-69e3-4030-a0ea-a0fb076b0d9f)
![kleo1](https://github.com/user-attachments/assets/1622933a-512c-49a8-ab32-619a42471d2f)


Photos for UI

2024-09-14 13:20 UTC, princedalsaniya requested changes

2024-09-14 13:20 UTC, princedalsaniya commented on src/App.tsx
> +                    <Navigate to={`/profile/{abc`} />
Please update this route, valid routes are
- `profile/${abc}`
- `profile/{abc}`
- `profile/abc`
This is invalid
-`profile{abc`

@vaibhavgeek ^^ what are we planning to redirect, I thought we used ${slug} that would be replaced with the slug from constant of user. This is not going to work all user redirected to `profile/{abc` what kind of route this is?

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/10percent.png
@devowl03 This should be real element not image.

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/87percent.png
@devowl03 This should be real element not image.

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/Bigstar.jsx
@devowl03 Please take reference from other svgs. We add svgs to assets and then import them like this.
`import {ReactComponent as ICON_NAME} from '../relative/path/to/svg';`

Now you can use ICON_NAME same as react component and give styling classes to them.

No need to create a whole component for just an svg for what just to give width and height, that you can give with tailwind classes. 

And how come this JSX ended up in images, assets are for assets like, img, jpeg, jpg, png, svg, gif there should never be any JSX or tsx.

@vaibhavgeek @devowl03

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/Data.png
If we need to add any images then have a practice to create a folder structure for that, like `assets/dashboard/xyzCard/copy.svg`

Keep this svg, we use SVG everywhere, so when we scale things up they don't look pixelated. So please use SVG for all icons.

@vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/Copy.png
Keep this svg, we use SVG everywhere, so when we scale things up they don't look pixelated. So please use SVG for all icons.

@vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/Frame 456 (1).png
Keep this svg, we use SVG everywhere, so when we scale things up they don't look pixelated. So please use SVG for all icons.

@vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/Frame 456 (1).png
Also give svg some meaning ful name , how come any other developer find this Frame456 meaning full? 

Please take into consideration these small good development practices. 

These are not things which you should get comments on, this is basic antiquates for development. Disappointing.

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/Graph.png
This has to be an complete component, in future when we integrate the API then what do we integrate it to? This Image. 

@vaibhavgeek ^^

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/Group.png
Keep this svg, we use SVG everywhere, so when we scale things up they don't look pixelated. So please use SVG for all icons. And keep them inside folders.

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/KLEO Logo.png
We already have many kleo logs please see if you can reuse the logo. Or we need a cleanup of the website.

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/KleoMate.jsx
Same goes for here too, use svg inside a folder and import it as ReactComponent. Not a good practice to keep jsx components in assets, along with a separate component which just renders an SVG only.

@vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/MediumStar.jsx
Same goes for here too, use svg inside a folder and import it as ReactComponent. Not a good practice to keep jsx components in assets, along with a separate component which just renders an SVG only.

@vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/SmallStar.jsx
Same goes for here too, use svg inside a folder and import it as ReactComponent. Not a good practice to keep jsx components in assets, along with a separate component which just renders an SVG only.

@vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/X.com.png
Same goes for here too, use svg inside a folder and import it as ReactComponent.

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/grid-png-43557.png
Same goes for here too, use svg inside a folder and import it as ReactComponent give a proper name to this.

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/grid-png-43559.png
Same goes for here too, use svg inside a folder and import it as ReactComponent. Give a proper name to this.

2024-09-14 13:20 UTC, princedalsaniya commented on src/assets/images/reward.png
Same goes for here too, use svg inside a folder and import it as ReactComponent.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/common/RadarChartComponent.tsx
> +  labels: ['Trading', 'Coding', 'Medicine', 'Government', 'Planning', 'Music', 'Podcasts', 'Designing'],
If we are making radar chart component then we should have these labels from an mock or const and replace it mimiking the API call, you can take reference from `slim-extension` PR, I have done that there correctly.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +  const DataQuality = () => {
Separate them out in separate files, under a folder structure like this,
dashboard
  - index.tsx
  - DataQualityCard.jsx
  - MilestoneCard.jsx
  - etc.
  
  this is unnecessarily making one file too large to manage.
  
  cc: @devowl03 @vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +function First() {
What is this name for a component? Component's name should always match the fileName or if fileName is index then match with folderName. Have this practice. What do we understand from this `First()`?

@devowl03 @vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          style={{ minHeight: '200px' }}
You can give this in tailwind class `min-h-[200px]` why use style for this? Use tailwind as much as you can.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          <div className="relative flex flex-col justify-between z-0 p-6" style={{ minHeight: '200px' }}>
no need for min-height 200px again, just use h-full.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +            <div>
you should have given this styles `text-lg font-medium font-inter` to this div directly and use custom styles like `text-4xl font-bold` for only 2400. This is unnecessary repetition of code. Very bad. 

Here is the ideal code for this part.
```
<div className="text-lg font-medium font-inter">
  <h3>Total Points Earned</h3>
  <p>
    <span className="text-4xl font-bold">{utilFunctionToAddComma(KleoPointsVariable)}</span>
    KLEO XP
  </p>
</div>
```

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +                2,400 <span className="text-lg text-lg font-medium font-inter">KLEO XP</span>
Use variable for this Kleo points, that is not a static value, changes per user. Please keep in mind the integration part. Not just having a landing page which never changes. Even there we use constant all the time because that is easy to update later.

@vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          style={{ minHeight: '215px' }}
Same goes here, use tailwind class min-h-[200px] why use style for this?

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +              34 MB <span className="text-lg font-medium font-inter">till date</span>
Same goes with here, use variable for dataQuantity. Ideally you should mock the API call in component, and just swap the API call when API is implemented, you should have the interfaces and placeholder where we return whole response which is stored in const to this dummy API call.

@devowl03 @vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          style={{ minHeight: '450px' }}
Change this to Tailwind Class everywhere.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +                backgroundColor: 'rgba(127, 86, 217, 1)'
Change this to Tailwind Class everywhere.
`bg-[customColorHex]`

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +              className="text-2xl flex items-center rounded-xl justify-center font-bold text-purple-600 w-20 h-16 bg-primary-btn-300 text-white p-10"
`bg-primary-btn-300` here you are giving background color then why give again in style?

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +              87%
Keep this a variable for API integration.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          <div className="mt-4 flex items-center justify-between">
Move this RadarChart component to it's own component, take reference from `slim-extension`.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +              <span
Why giving inlineStyle? Use tailwind for this. Its simple classes bro.
`h-[11px] w-[11px] bg-white p-[1px] flex justify-center items-center mr-1 rounded-[50%]`

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +              ></span>{' '}
Remove this part, they are garbage, if you copy from figma then they comes but you should remove them.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +              Designing
Keep this a variable for API integration.

Also this should be inside the Radarchart component and you should calculate this instead of just directly hard-coding this.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +        // style={{ width: '500px', right: '70px' }}
Remove this.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +        style={{ maxHeight: '450px' }}
use tailwind class.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +                alt="Tweet your activity graph"
we can use svg for this instead of img. Imported as ReactComponent.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +              <img
Keep this an element where you pass on the percentage.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +              <img
Keep this an element where you pass on the percentage.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          <li className="flex items-center rounded-lg px-2 justify-between h-16 bg-gray-100 opacity-50">
Ideally you should create a component where you take up this first icon, text, isDisabled, coinsCount etc. And reuse them this is very bad, now if we need to change a simple style then I have to change in all 4 manually.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          {/* <!-- First Card - Kleo Mate --> */}
Create separate component and take image, title, content, backgroundColor and button text as input and re-use. 

This is very bad practice to keep repeating the same code for the cards which are completely same except for the bg-color but that can be handled with input right.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +            style={{ backgroundColor: '#293056' }}
use tailwind class.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +            <div className="flex items-center space-x-1 rounded-full bg-black px-3 py-2">
You should have cursor-pointer here, as this is working as button. Ideally this should have been button from start, not a div.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +            <div className="flex items-center space-x-1 rounded-full bg-black px-3 py-2">
We need to add onClick and some function here. So change this to button. First pill can be div.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +        <div className="mt-4 max-h-44 overflow-y-auto">
This whole table is a separate component, so we can make it's API call separately. And asking you to make components as much as you can because this reduces re-renders for other part, if we re-render this table then whole page is re-rendering here as this is same component. 

@devowl03 @vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +                    {referral.dateJoined}
Date won't come in your expected format, so you would to use a utils function to convert it. Ideally dates come like `1234567` number, or `MM-dd-YYYY` format. So take any of this simple ones, this conversion should be handled on FE not BE.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +            <li
Separate the row from leaderboard and re-use it.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +              onClick={() => handleClick(index)}
give this a proper name, handleClick can be anywhere on page. it should be like `handleLeaderBoardRowClick()` or something

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +                  className={`text-xs font-medium ${selectedIndex === index ? 'text-white' : 'text-gray-700'
This component is not styles with prettier, other wise this `}\`}` won't come in separate line. So please use formatters like prettiers.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +                {data.reward}{' '}
remove this {' '}

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +  const Privacy = () => {
Separate card component as explained earlier.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          background:
Give this gradient in tailwind

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          2,400 <span className="text-white text-lg font-normal">PIIS </span>
This is a variable not something to hardcode. Please use API content here.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +  const Leader = () => {
Give a proper name, like `LeaderBoardBanner` as it is. And separate it to new component.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          background:
use  tailwind.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +          style={{
use tailwind.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +        style={{ backgroundColor: 'rgba(248, 249, 252, 1)' }}
use tailwind.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +    <div className="bg-slate-100">
This is a navbar so please use separate component and create it as Navbar not a part of this page, and add logic for highlighting active route link instead of hardCoding it. 

This is clearly a new UI and new UI has new Navbar, so how come you can put it inside a component bro, this goes without saying that new navbar has to be created.

@devowl03 @vaibhavgeek

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +const LeaderBoardData = [
Move all of these to a constant file create separate file name `dashboard.constants.ts`. And move them there.

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +const options = {
These goes into `radardChart.constants.ts`

2024-09-14 13:20 UTC, princedalsaniya commented on src/components/profile/index.tsx
> +// import React, { useState } from 'react';
Remove this commented code, don't need in deployed version, If we need to bring it back we can alway get it from PRs.

2024-09-17 09:20 UTC, vaibhavgeek commented on src/App.tsx
> +                    <Navigate to={`/profile/{abc`} />
`profile/${user.slug}`

2024-09-17 10:40 UTC, princedalsaniya requested changes

2024-09-17 10:40 UTC, princedalsaniya commented on src/components/profile/components/LeaderboardRow.tsx
> +                    src="https://picsum.photos/40"
@devowl03 You need to take this profilePic, or now when we are using metamask now then generated image from data. This is unique for each user in leaderboard, can't keep same for everyone.

@vaibhavgeek please confirm the requirements.

2024-09-17 10:40 UTC, princedalsaniya commented on src/components/profile/components/Leaderboard.tsx
>          { id: '288', name: 'Ruchi Tripathi', reward: '213' },
Make an Interface for this data, don't just assign data directly, in future when we integrate API we can update the interface too.

And keep practice for having these constants and mocks in common separate file. If you want to keep it here, then keep it outside `Leaderboard` function, this are reassigning on every re-render.

2024-09-17 10:40 UTC, princedalsaniya commented on src/components/profile/components/Leaderboard.tsx
>          { id: '1', name: 'Alex Johnson', reward: '180' },
Add Profile Picture field here.

2024-09-17 10:40 UTC, princedalsaniya commented on src/components/profile/components/Milestones.tsx
> +const ListItem: React.FC<ListItemProps> = ({
Everywhere we are using the function/component declaration like this.
`const ListItem = ({ destructureProps }: ListItemProps) {...}`

Then why are you using this `React.FC<type>` declaration? Any specific reason?

2024-09-17 10:40 UTC, princedalsaniya commented on src/components/profile/components/Milestones.tsx
> +const CircularProgress = ({ percentage }) => {
Give a type here, at-least give number or string. please.

2024-09-17 10:40 UTC, princedalsaniya commented on src/components/profile/components/Milestones.tsx
> +      <ul className="mt-4 pb-8 space-y-4">
You could have made an array and mapped over it, instead of keep repeating this code. Please do that.

2024-09-17 10:40 UTC, princedalsaniya commented on src/components/profile/components/Navbar.tsx
> +            src={'https://picsum.photos/40'}
Use actual profile Picture. Not placeholder.

2024-09-17 10:40 UTC, princedalsaniya commented on src/components/profile/components/ReferalTable.tsx
> +                src={'https://picsum.photos/40'}
Same goes here, add image in mock data array referral.

2024-09-21 03:25 UTC, princedalsaniya approved these changes

2024-09-21 16:38 UTC, merged